### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by marcelklehr** [vidigami/backbone-sql#20]
I get this error on the server when creating an entity with a relation .

**Comment by kmalakoff** [comment]
I would need to see the hierarchy of your schema, eg. each model and schema

**Comment by marcelklehr** [comment]
```js
app.Device = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/devices'
, schema: {
    location: function() { return ['belongsTo', app.Location]; }
  , product: function() { return ['belongsTo', app.Product]; }
  , retailer: function() { return ['belongsTo', app.Retailer]; }
  , serialNumber: 'String'
  , lranr: 'String'
  , price: 'String'
  , acquisitionDate: 'String'
  , comment: 'String'
  }
})

app.DeviceType = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/deviceTypes'
, schema: {
    products: function() { return ['hasMany', app.Product]; }
  , name: 'String'
  }
})

app.Location = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/locations'
, schema: {
    devices: function() {return ['hasMany', app.Device]}
  , name: 'String'
  }
})

app.Product = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/products'
, schema: {
    device_type: function() { return ['belongsTo', app.DeviceType]; }
  , devices: function() { return ['hasMany', app.Device]; }
  , manufacturer: 'String'
  , name: 'String'
  , productId: 'String'
  }
})

app.Retailer = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/retailers'
, schema: {
    devices: function() {return ['hasMany', app.Device]}
  , name: 'String'
  }
})
```

**Comment by marcelklehr** [comment]
It seems to create models excessively, but the Backbone.Model constructor is not the source of the recursion.

**Comment by marcelklehr** [comment]
Looking through the stack at some breakpoint that I set, I can make out that creating a new deviceType triggers an "add" event, which triggers a "change:devic_type" event, which then again triggers an "add" event, and so on.

**Comment by marcelklehr** [comment]
For testing purposes I have a file that creates all the entities. This is the code that creates them:

```js
var app = require('./')

var r219 = new app.Location({name: "219"})
r219.save()

var r067 = new app.Location({name: "067"})
r067.save()



var retAlmsdorf = new app.Retailer({name: 'Almsdorf'})
retAlmsdorf.save()

var retOtto = new app.Retailer({name: 'Ottos Elektroladen'})
retOtto.save()

var retQuelle = new app.Retailer({name: 'Quelle'})
retQuelle.save()

var retMediamarkt = new app.Retailer({name: 'Mediamarkt'})
retMediamarkt.save()


var typMonitor = new app.DeviceType({name: 'Monitor'})
console.log('saving typMonitor')
typMonitor.save(function(er) {
  console.log(er)
  var iiyama = new app.Product({
    name: 'ProLite'
  , productId: 'E1906S' // vllt. gehört hier auch noch 'prolite' dazu? k.a.
  , manufacturer: 'Iiyama'
  , device_type: typMonitor
  })
  console.log('saving iiyama')
  iiyama.save(function(er) {
    console.log(er)
    ;[['10CZC2275J1J', 'LRA028623', retAlmsdorf, '07/2012', r067]
    , ['10CZC2275J1F', 'LRA028624', retOtto, '07/2012', r219]
    , ['10CZC2275J15', 'LRA028625', retQuelle, '07/2012', r219]
    ].forEach(function(record) {
      (function
       (serialId ,     lranummer ,     retailer   , acquisitionDate, room) {
        var monitor = new app.Device({
          product: iiyama
        , serialNumber: serialId
        , location: room
        , lranr: lranummer
        , retailer: retailer
        , acquisitionDate: acquisitionDate

        , price: '€7,42'
        , comment: ''
        })
        console.log('saving '+lranummer)
        monitor.save()
      }).apply(null, record)
    })

  })

})

var typPC = new app.DeviceType({name: 'PC'})
typPC.save(function() {


  var hpcompaq = new app.Product({
    name: 'Compaq'
  , productId: '8200Elite' // vllt. gehört hier auch noch 'compaq' dazu? k.a.
  , manufacturer: 'HP'
  , device_type: typPC
  })
  hpcompaq.save(function() {

    ;[['10CZC2275J1C', 'LRA028637', retMediamarkt, '07/2012', r067]
    , ['10CZC2275J10', 'LRA028638', retQuelle, '07/2012', r219]
    , ['10CZC2275J1G', 'LRA028639', retAlmsdorf, '07/2012', r219]
    ].forEach(function(record) {
      (function
       (serialId ,     lranummer ,     retailer   , acquisitionDate, room) {
        var pc = new app.Device({
          product: hpcompaq
        , serialNumber: serialId
        , location: room
        , lranr: lranummer
        , retailer: retailer
        , acquisitionDate: acquisitionDate

        , price: '$7,45'
        , comment: ''
        })
        pc.save()
      }).apply(null, record)
    })

  })

})
```

**Comment by kmalakoff** [comment]
I'm looking at your saving code. It should be fully asynchronous, eg. I see that sometimes you are not waiting for the model save to complete (where they will be assigned an id).

I'll look into getting your code working.

**Comment by kmalakoff** [comment]
I've tried to get your code working and made some modifications:

1) added a sync method - it looks like the code was missing the step of setting the BackboneSQL sync.

2) added a create function - make sure the schemas exist

3) updated to our naming convention - deviceTypes changed to device_types. I'm not sure if this matters.

I think your code is working now even without the changes to first save all dependent models (from my previous response). You can try using the Queue module bundled with BackboneORM or Async or whatever your control flow preference is to ensure the correct saving flow.

Did this help resolve everything?


models.js

```
var Backbone = require('backbone');
var BackboneSQL = require('backbone-sql');

var app = module.exports = {};

app.Device = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/devices'
, schema: {
    location: function() { return ['belongsTo', app.Location]; }
  , product: function() { return ['belongsTo', app.Product]; }
  , retailer: function() { return ['belongsTo', app.Retailer]; }
  , serialNumber: 'String'
  , lranr: 'String'
  , price: 'String'
  , acquisitionDate: 'String'
  , comment: 'String'
  }
})
app.Device.prototype.sync = BackboneSQL.sync(app.Device);

app.DeviceType = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/device_types'
, schema: {
    products: function() { return ['hasMany', app.Product]; }
  , name: 'String'
  }
})
app.DeviceType.prototype.sync = BackboneSQL.sync(app.DeviceType);

app.Location = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/locations'
, schema: {
    devices: function() {return ['hasMany', app.Device]}
  , name: 'String'
  }
})
app.Location.prototype.sync = BackboneSQL.sync(app.Location);

app.Product = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/products'
, schema: {
    device_type: function() { return ['belongsTo', app.DeviceType]; }
  , devices: function() { return ['hasMany', app.Device]; }
  , manufacturer: 'String'
  , name: 'String'
  , productId: 'String'
  }
})
app.Product.prototype.sync = BackboneSQL.sync(app.Product);

app.Retailer = Backbone.Model.extend({
  url: 'sqlite3://db.sqlite/retailers'
, schema: {
    devices: function() {return ['hasMany', app.Device]}
  , name: 'String'
  }
})
app.Retailer.prototype.sync = BackboneSQL.sync(app.Retailer);
```

create.js

```
var app, model, name, _fn;

app = require('./models');

_fn = function(name, model) {
  return model.db().ensureSchema(function(err) {
    return console.log("Created " + name + ". Error: " + err);
  });
};
for (name in app) {_fn(name, app[name]);}
```

save.js

```
var app = require('./models');

var r219 = new app.Location({name: "219"})
r219.save()

var r067 = new app.Location({name: "067"})
r067.save()



var retAlmsdorf = new app.Retailer({name: 'Almsdorf'})
retAlmsdorf.save()

var retOtto = new app.Retailer({name: 'Ottos Elektroladen'})
retOtto.save()

var retQuelle = new app.Retailer({name: 'Quelle'})
retQuelle.save()

var retMediamarkt = new app.Retailer({name: 'Mediamarkt'})
retMediamarkt.save()


var typMonitor = new app.DeviceType({name: 'Monitor'})
console.log('saving typMonitor')
typMonitor.save(function(er) {
  console.log(er)
  var iiyama = new app.Product({
    name: 'ProLite'
  , productId: 'E1906S' // vllt. gehört hier auch noch 'prolite' dazu? k.a.
  , manufacturer: 'Iiyama'
  , device_type: typMonitor
  })
  console.log('saving iiyama')
  iiyama.save(function(er) {
    console.log(er)
    ;[['10CZC2275J1J', 'LRA028623', retAlmsdorf, '07/2012', r067]
    , ['10CZC2275J1F', 'LRA028624', retOtto, '07/2012', r219]
    , ['10CZC2275J15', 'LRA028625', retQuelle, '07/2012', r219]
    ].forEach(function(record) {
      (function
       (serialId ,     lranummer ,     retailer   , acquisitionDate, room) {
        var monitor = new app.Device({
          product: iiyama
        , serialNumber: serialId
        , location: room
        , lranr: lranummer
        , retailer: retailer
        , acquisitionDate: acquisitionDate

        , price: '€7,42'
        , comment: ''
        })
        console.log('saving '+lranummer)
        monitor.save()
      }).apply(null, record)
    })

  })

})

var typPC = new app.DeviceType({name: 'PC'})
typPC.save(function() {


  var hpcompaq = new app.Product({
    name: 'Compaq'
  , productId: '8200Elite' // vllt. gehört hier auch noch 'compaq' dazu? k.a.
  , manufacturer: 'HP'
  , device_type: typPC
  })
  hpcompaq.save(function() {

    ;[['10CZC2275J1C', 'LRA028637', retMediamarkt, '07/2012', r067]
    , ['10CZC2275J10', 'LRA028638', retQuelle, '07/2012', r219]
    , ['10CZC2275J1G', 'LRA028639', retAlmsdorf, '07/2012', r219]
    ].forEach(function(record) {
      (function
       (serialId ,     lranummer ,     retailer   , acquisitionDate, room) {
        var pc = new app.Device({
          product: hpcompaq
        , serialNumber: serialId
        , location: room
        , lranr: lranummer
        , retailer: retailer
        , acquisitionDate: acquisitionDate

        , price: '$7,45'
        , comment: ''
        })
        pc.save()
      }).apply(null, record)
    })

  })

})
```

**Comment by marcelklehr** [comment]
I published my repo on github, so I don't have to post stuff in here. See https://github.com/marcelklehr/ger-temanager/tree/nw/code for the code with in-memory storage and https://github.com/marcelklehr/ger-temanager/tree/sqlite/code for the same app with sqlite storage.

Both trees don't work at the moment. The app is supposed to run in [nw.js](https://github.com/nwjs/nw.js), thus the `requireNode`, which is node's require and `require` which is component's require.
In `nw` I get an error that product.get is undefined (after doing a `device.get('product')`), shouldn't get(relation) return a full-featured Model instance? (This used to work...)
In `nw` TestData.js doesn't pass and yields the aforementioned RangeError...

I hope you can shed some light into the dark :fireworks: :)

**Comment by marcelklehr** [comment]
`nw` works like a charm for me now, no idea what caused that error. Still, `sqlite` branch still exhibits the RangeError

**Comment by marcelklehr** [comment]
Perhaps, it's easier for you if I give you a little introduction:
[code/lib/](https://github.com/marcelklehr/ger-temanager/tree/sqlite/code/lib) contains all Backbone models and views. E.g. [code/lib/Device/index.js](https://github.com/marcelklehr/ger-temanager/blob/sqlite/code/lib/Device/index.js) contains the Model code for Devices. The test data is created in [code/lib/TestData.js](https://github.com/marcelklehr/ger-temanager/blob/sqlite/code/lib/TestData.js) and the kick-off code is in [code/lib/index.js](https://github.com/marcelklehr/ger-temanager/blob/sqlite/code/lib/index.js#L343)

What am I missing?

**Comment by marcelklehr** [comment]
This is the stack:
```
RangeError: Maximum call stack size exceeded
    at Function._.extend (code/build/build.js:2761:18)
    at Function._.clone (code/build/build.js:2816:45)
    at _.extend.set (code/build/build.js:558:38)
    at overrides.set (code\node_modules\backbone-sql\node_modules\backbone-orm\backbone-orm.js:6085:53)
    at Backbone.Model (code/build/build.js:475:10)
    at new child (code/build/build.js:1872:41)
    at Collection._.extend._prepareModel (code\node_modules\backbone-sql\node_modules\backbone\backbone.js:915:19)
    at Collection.overrides._prepareModel (code\node_modules\backbone-sql\node_modules\backbone-orm\backbone-orm.js:9149:71)
    at Collection._.extend.set (code\node_modules\backbone-sql\node_modules\backbone\backbone.js:706:36)
    at Collection._.extend.add (code\node_modules\backbone-sql\node_modules\backbone\backbone.js:638:19)
```

**Comment by marcelklehr** [comment]
I think the bug is due to node-webkit's separate execution contexts for node and webkit...

**Comment by kmalakoff** [comment]
Sorry that I couldn't help more.
